 INSERT INTO departamento (cod, nome) VALUES (1, 'Administrativo');
 INSERT INTO departamento (cod, nome) VALUES (2, 'Financeiro');
 INSERT INTO departamento (cod, nome) VALUES (3, 'Recursos humanos');
 INSERT INTO departamento (cod, nome) VALUES (4, 'Comercial');
 INSERT INTO departamento (cod, nome) VALUES (5, 'Logistica');
 
 INSERT INTO funcionario (cod, cod_departamento, nome, dependentes, salario, cargo) VALUES (1, 1, 'Jacqueline Mars', 3, 28242.60, 'Diretor'); 
 INSERT INTO funcionario (cod, cod_departamento, nome, dependentes, salario, cargo) VALUES (2, 1, 'Júlio César', 1, 14121.30, 'Gerente');
 INSERT INTO funcionario (cod, cod_departamento, nome, dependentes, salario, cargo) VALUES (3, 1, 'Tito Labieno', 2, 5648.52, 'Analista');
 INSERT INTO funcionario (cod, cod_departamento, nome, dependentes, salario, cargo) VALUES (4, 1, 'Décimo Júnio Bruto Albino', 0, 3530.33, 'Assistente');
 INSERT INTO funcionario (cod, cod_departamento, nome, dependentes, salario, cargo) VALUES (5, 1, 'Gina Rinehart', 2, 3530.33, 'Assistente');
 INSERT INTO funcionario (cod, cod_departamento, nome, dependentes, salario, cargo) VALUES (6, 2, 'João Macciconni', 0, 28242.60, 'Diretor'); 
 INSERT INTO funcionario (cod, cod_departamento, nome, dependentes, salario, cargo) VALUES (7, 2, 'Julia Koch', 3, 14121.30, 'Gerente');
 INSERT INTO funcionario (cod, cod_departamento, nome, dependentes, salario, cargo) VALUES (8, 2, 'Françoise Bettencourt Meyers', 1, 5648.52, 'Analista');
 INSERT INTO funcionario (cod, cod_departamento, nome, dependentes, salario, cargo) VALUES (9, 2, 'Richard Wagner', 2, 3530.33, 'Assistente');
 INSERT INTO funcionario (cod, cod_departamento, nome, dependentes, salario, cargo) VALUES (10, 3, 'Helena Kolody', 0, 28242.60, 'Diretor'); 
 INSERT INTO funcionario (cod, cod_departamento, nome, dependentes, salario, cargo) VALUES (11, 3, 'Emiliano Perneta', 3, 14121.30, 'Gerente');
 INSERT INTO funcionario (cod, cod_departamento, nome, dependentes, salario, cargo) VALUES (12, 3, 'Cristóvão Tezza', 1, 5648.52, 'Analista');
 INSERT INTO funcionario (cod, cod_departamento, nome, dependentes, salario, cargo) VALUES (13, 3, 'Manuel Bandeira', 2, 3530.33, 'Assistente');
 INSERT INTO funcionario (cod, cod_departamento, nome, dependentes, salario, cargo) VALUES (14, 4, 'José de Alencar', 2, 3530.33, 'Assistente');
 INSERT INTO funcionario (cod, cod_departamento, nome, dependentes, salario, cargo) VALUES (15, 4, 'Clarice Lispector', 1, 3530.33, 'Assistente');
 INSERT INTO funcionario (cod, cod_departamento, nome, dependentes, salario, cargo) VALUES (16, 4, 'Lygia Fagundes Telles', 0, 3530.33, 'Assistente');
 INSERT INTO funcionario (cod, cod_departamento, nome, dependentes, salario, cargo) VALUES (17, 4, 'Johann Sebastian Bach', 4, 28242.60, 'Diretor'); 
 INSERT INTO funcionario (cod, cod_departamento, nome, dependentes, salario, cargo) VALUES (18, 4, 'Ludwing Van Beethowen', 3, 14121.30, 'Gerente');
 INSERT INTO funcionario (cod, cod_departamento, nome, dependentes, salario, cargo) VALUES (19, 4, 'Frederic Chopin', 1, 5648.52, 'Analista');
 INSERT INTO funcionario (cod, cod_departamento, nome, dependentes, salario, cargo) VALUES (20, 4, 'Franz Schubert', 2, 5648.52, 'Analista');
 INSERT INTO funcionario (cod, cod_departamento, nome, dependentes, salario, cargo) VALUES (21, 4, 'Johannes Brahms', 2, 5648.52, 'Analista');
 INSERT INTO funcionario (cod, cod_departamento, nome, dependentes, salario, cargo) VALUES (22, 4, 'Manuel Deodoro da Fonseca', 1, 5648.52, 'Analista');
 INSERT INTO funcionario (cod, cod_departamento, nome, dependentes, salario, cargo) VALUES (23, 4, 'Floriano Vieira Peixoto', 0, 5648.52, 'Analista');
 INSERT INTO funcionario (cod, cod_departamento, nome, dependentes, salario, cargo) VALUES (24, 4, 'Katie Bouman', 2, 3530.33, 'Assistente');
 INSERT INTO funcionario (cod, cod_departamento, nome, dependentes, salario, cargo) VALUES (25, 4, 'Ada Lovelace', 1, 3530.33, 'Assistente');
 INSERT INTO funcionario (cod, cod_departamento, nome, dependentes, salario, cargo) VALUES (26, 4, 'Mary Jackson', 0, 3530.33, 'Assistente');
 INSERT INTO funcionario (cod, cod_departamento, nome, dependentes, salario, cargo) VALUES (27, 5, 'Mae Jemison', 3, 14121.30, 'Gerente');
 INSERT INTO funcionario (cod, cod_departamento, nome, dependentes, salario, cargo) VALUES (28, 5, 'Karen Horney', 1, 5648.52, 'Analista');
 INSERT INTO funcionario (cod, cod_departamento, nome, dependentes, salario, cargo) VALUES (29, 5, 'Campos Sales', 2, 3530.33, 'Assistente');
 INSERT INTO funcionario (cod, cod_departamento, nome, dependentes, salario, cargo) VALUES (30, 5, 'Venceslau Brás', 1, 5648.52, 'Analista');
 INSERT INTO funcionario (cod, cod_departamento, nome, dependentes, salario, cargo) VALUES (31, 1, 'Gengis Khan', 5, 40951.77, 'Presidente'); 
 INSERT INTO funcionario (cod, cod_departamento, nome, dependentes, salario, cargo) VALUES (32, 1, 'Dirlei Afonso', 2, 5648.52, 'Analista'); 
 INSERT INTO funcionario (cod, cod_departamento, nome, dependentes, salario, cargo) VALUES (33, 3, 'Dirmalinda Maria Pereira', 1, 5648.52, 'Analista'); 